// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Header Links → Links*
 */
export interface HeaderLinksDocumentDataLinksItem {
  /**
   * Icon field in *Header Links → Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header_links.links[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Href field in *Header Links → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_links.links[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField;
}

type HeaderLinksDocumentDataSlicesSlice = NotificationSlice;

/**
 * Content for Header Links documents
 */
interface HeaderLinksDocumentData {
  /**
   * Links field in *Header Links*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header_links.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<HeaderLinksDocumentDataLinksItem>>;

  /**
   * Search field in *Header Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_links.search
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  search: prismic.KeyTextField;

  /**
   * Submit Work field in *Header Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_links.submit_work
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  submit_work: prismic.KeyTextField;

  /**
   * Register field in *Header Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_links.register
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  register: prismic.KeyTextField;

  /**
   * Slice Zone field in *Header Links*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header_links.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeaderLinksDocumentDataSlicesSlice>;
}

/**
 * Header Links document from Prismic
 *
 * - **API ID**: `header_links`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderLinksDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderLinksDocumentData>,
    "header_links",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | FaqSlice
  | TeamSlice
  | SubscribeSlice
  | TutorialSlice
  | TestimonialSlice
  | PopularWebsitesSlice
  | HotTrendSlice
  | HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for Website Detail documents
 */
interface WebsiteDetailDocumentData {
  /**
   * Nominated field in *Website Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_detail.nominated
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nominated: prismic.KeyTextField;

  /**
   * Vote field in *Website Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_detail.vote
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vote: prismic.KeyTextField;

  /**
   * Share field in *Website Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_detail.share
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  share: prismic.KeyTextField;

  /**
   * Copy Link field in *Website Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_detail.copy_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copy_link: prismic.KeyTextField;

  /**
   * Views field in *Website Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_detail.views
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  views: prismic.KeyTextField;

  /**
   * Description field in *Website Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_detail.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Vision field in *Website Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_detail.vision
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  vision: prismic.KeyTextField;

  /**
   * Typography field in *Website Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_detail.typography
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  typography: prismic.KeyTextField;

  /**
   * Color Palette field in *Website Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_detail.color_palette
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  color_palette: prismic.KeyTextField;

  /**
   * Tags field in *Website Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_detail.tags
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tags: prismic.KeyTextField;

  /**
   * Other Screens of the Website field in *Website Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_detail.other_screens_of_the_website
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  other_screens_of_the_website: prismic.KeyTextField;

  /**
   * Designer Information field in *Website Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_detail.designer_information
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  designer_information: prismic.KeyTextField;

  /**
   * Similar Collections field in *Website Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_detail.similar_collections
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  similar_collections: prismic.KeyTextField;
}

/**
 * Website Detail document from Prismic
 *
 * - **API ID**: `website_detail`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WebsiteDetailDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<WebsiteDetailDocumentData>,
    "website_detail",
    Lang
  >;

export type AllDocumentTypes =
  | HeaderLinksDocument
  | HomeDocument
  | WebsiteDetailDocument;

/**
 * Item in *Faq → Default → Primary → Questions*
 */
export interface FaqSliceDefaultPrimaryQuestionsItem {
  /**
   * Question field in *Faq → Default → Primary → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questions[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *Faq → Default → Primary → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questions[].answer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer: prismic.KeyTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Title field in *Faq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Faq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Questions field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questions[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  questions: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryQuestionsItem>>;

  /**
   * Questioning Title field in *Faq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questioning_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  questioning_title: prismic.KeyTextField;

  /**
   * Questioning Description field in *Faq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questioning_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  questioning_description: prismic.KeyTextField;

  /**
   * Questioning Link field in *Faq → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.questioning_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  questioning_link: prismic.LinkField;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title 1 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_1: prismic.KeyTextField;

  /**
   * Title 2 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_2: prismic.KeyTextField;

  /**
   * Title 3 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title_3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_3: prismic.KeyTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Featuring Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.featuring_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  featuring_title: prismic.KeyTextField;

  /**
   * Featuring Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.featuring_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featuring_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *HotTrend → Default → Primary*
 */
export interface HotTrendSliceDefaultPrimary {
  /**
   * Header field in *HotTrend → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hot_trend.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * Title field in *HotTrend → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hot_trend.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *HotTrend → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hot_trend.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for HotTrend Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HotTrendSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HotTrendSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HotTrend*
 */
type HotTrendSliceVariation = HotTrendSliceDefault;

/**
 * HotTrend Shared Slice
 *
 * - **API ID**: `hot_trend`
 * - **Description**: HotTrend
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HotTrendSlice = prismic.SharedSlice<
  "hot_trend",
  HotTrendSliceVariation
>;

/**
 * Primary content in *Notification → Default → Primary*
 */
export interface NotificationSliceDefaultPrimary {
  /**
   * Icon field in *Notification → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: notification.default.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *Notification → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: notification.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Notification → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: notification.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Gradient 1 field in *Notification → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: notification.default.primary.gradient_1
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  gradient_1: prismic.ColorField;

  /**
   * Gradient 2 field in *Notification → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: notification.default.primary.gradient_2
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  gradient_2: prismic.ColorField;
}

/**
 * Default variation for Notification Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NotificationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NotificationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Notification*
 */
type NotificationSliceVariation = NotificationSliceDefault;

/**
 * Notification Shared Slice
 *
 * - **API ID**: `notification`
 * - **Description**: Notification
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NotificationSlice = prismic.SharedSlice<
  "notification",
  NotificationSliceVariation
>;

/**
 * Primary content in *PopularWebsites → Default → Primary*
 */
export interface PopularWebsitesSliceDefaultPrimary {
  /**
   * Header field in *PopularWebsites → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: popular_websites.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * Title field in *PopularWebsites → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: popular_websites.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for PopularWebsites Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopularWebsitesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PopularWebsitesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PopularWebsites*
 */
type PopularWebsitesSliceVariation = PopularWebsitesSliceDefault;

/**
 * PopularWebsites Shared Slice
 *
 * - **API ID**: `popular_websites`
 * - **Description**: PopularWebsites
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PopularWebsitesSlice = prismic.SharedSlice<
  "popular_websites",
  PopularWebsitesSliceVariation
>;

/**
 * Primary content in *Subscribe → Default → Primary*
 */
export interface SubscribeSliceDefaultPrimary {
  /**
   * Title field in *Subscribe → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscribe.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Subscribe → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscribe.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Agreement field in *Subscribe → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subscribe.default.primary.agreement
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  agreement: prismic.KeyTextField;

  /**
   * Link field in *Subscribe → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: subscribe.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Subscribe Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubscribeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SubscribeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Subscribe*
 */
type SubscribeSliceVariation = SubscribeSliceDefault;

/**
 * Subscribe Shared Slice
 *
 * - **API ID**: `subscribe`
 * - **Description**: Subscribe
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubscribeSlice = prismic.SharedSlice<
  "subscribe",
  SubscribeSliceVariation
>;

/**
 * Item in *Team → Default → Primary → Members*
 */
export interface TeamSliceDefaultPrimaryMembersItem {
  /**
   * Name field in *Team → Default → Primary → Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.members[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Position field in *Team → Default → Primary → Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.members[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * Profile field in *Team → Default → Primary → Members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.members[].profile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile: prismic.ImageField<never>;

  /**
   * Message field in *Team → Default → Primary → Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.members[].message
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  message: prismic.KeyTextField;

  /**
   * LinkedIn field in *Team → Default → Primary → Members*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.members[].linkedin
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin: prismic.LinkField;

  /**
   * Twitter field in *Team → Default → Primary → Members*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.members[].twitter
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  twitter: prismic.LinkField;

  /**
   * Dribbble field in *Team → Default → Primary → Members*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.members[].dribbble
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  dribbble: prismic.LinkField;
}

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Title field in *Team → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Team → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Members field in *Team → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.members[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  members: prismic.GroupField<Simplify<TeamSliceDefaultPrimaryMembersItem>>;

  /**
   * Notification Title field in *Team → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.notification_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  notification_title: prismic.KeyTextField;

  /**
   * Notification Description field in *Team → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.notification_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  notification_description: prismic.KeyTextField;

  /**
   * Notification Link field in *Team → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.notification_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  notification_link: prismic.LinkField;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

/**
 * Item in *Testimonial → Default → Primary → Feedbacks*
 */
export interface TestimonialSliceDefaultPrimaryFeedbacksItem {
  /**
   * user field in *Testimonial → Default → Primary → Feedbacks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.feedbacks[].user
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  user: prismic.KeyTextField;

  /**
   * profile field in *Testimonial → Default → Primary → Feedbacks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.feedbacks[].profile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile: prismic.ImageField<never>;

  /**
   * Occupation field in *Testimonial → Default → Primary → Feedbacks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.feedbacks[].occupation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  occupation: prismic.KeyTextField;

  /**
   * Description field in *Testimonial → Default → Primary → Feedbacks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.feedbacks[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Rating field in *Testimonial → Default → Primary → Feedbacks*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.feedbacks[].rating
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  rating: prismic.NumberField;
}

/**
 * Primary content in *Testimonial → Default → Primary*
 */
export interface TestimonialSliceDefaultPrimary {
  /**
   * Header field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * Feedbacks field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.feedbacks[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  feedbacks: prismic.GroupField<
    Simplify<TestimonialSliceDefaultPrimaryFeedbacksItem>
  >;
}

/**
 * Default variation for Testimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonial*
 */
type TestimonialSliceVariation = TestimonialSliceDefault;

/**
 * Testimonial Shared Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: Testimonial
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialSlice = prismic.SharedSlice<
  "testimonial",
  TestimonialSliceVariation
>;

/**
 * Primary content in *Tutorial → Default → Primary*
 */
export interface TutorialSliceDefaultPrimary {
  /**
   * Image field in *Tutorial → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tutorial.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Header field in *Tutorial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tutorial.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * Title field in *Tutorial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tutorial.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Tutorial → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tutorial.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Link field in *Tutorial → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tutorial.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Tutorial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TutorialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TutorialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Tutorial*
 */
type TutorialSliceVariation = TutorialSliceDefault;

/**
 * Tutorial Shared Slice
 *
 * - **API ID**: `tutorial`
 * - **Description**: Tutorial
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TutorialSlice = prismic.SharedSlice<
  "tutorial",
  TutorialSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HeaderLinksDocument,
      HeaderLinksDocumentData,
      HeaderLinksDocumentDataLinksItem,
      HeaderLinksDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      WebsiteDetailDocument,
      WebsiteDetailDocumentData,
      AllDocumentTypes,
      FaqSlice,
      FaqSliceDefaultPrimaryQuestionsItem,
      FaqSliceDefaultPrimary,
      FaqSliceVariation,
      FaqSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HotTrendSlice,
      HotTrendSliceDefaultPrimary,
      HotTrendSliceVariation,
      HotTrendSliceDefault,
      NotificationSlice,
      NotificationSliceDefaultPrimary,
      NotificationSliceVariation,
      NotificationSliceDefault,
      PopularWebsitesSlice,
      PopularWebsitesSliceDefaultPrimary,
      PopularWebsitesSliceVariation,
      PopularWebsitesSliceDefault,
      SubscribeSlice,
      SubscribeSliceDefaultPrimary,
      SubscribeSliceVariation,
      SubscribeSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimaryMembersItem,
      TeamSliceDefaultPrimary,
      TeamSliceVariation,
      TeamSliceDefault,
      TestimonialSlice,
      TestimonialSliceDefaultPrimaryFeedbacksItem,
      TestimonialSliceDefaultPrimary,
      TestimonialSliceVariation,
      TestimonialSliceDefault,
      TutorialSlice,
      TutorialSliceDefaultPrimary,
      TutorialSliceVariation,
      TutorialSliceDefault,
    };
  }
}
