// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  hot_trend: dynamic(() => import("./HotTrend")),
  popular_websites: dynamic(() => import("./PopularWebsites")),
  subscribe: dynamic(() => import("./Subscribe")),
  team: dynamic(() => import("./Team")),
  testimonial: dynamic(() => import("./Testimonial")),
  tutorial: dynamic(() => import("./Tutorial")),
};
